package epr001project;

import Report.GeneratorReport;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableCellRenderer;


/**
 *
 * @author leoam14
 */
public class Empreendimento extends javax.swing.JPanel {

    /**
     * Creates new form Empreendimento
     */
    JFrame j;
    public Empreendimento(JFrame j) {
        initComponents();
        Data.getData().dadosModel.calculaValores();
        Data.getData().dadosModel.updateData();
        this.j = j;
        JPanel pt = this;
//        DadosModel dataTable = new DadosModel();
//        JTable tabela = new JTable(dataTable);
//        JScrollPane scroll = new JScrollPane();
//        scroll.add(tabela);
//        scroll.setSize(500,500);
//        this.add(scroll);
        
        final JFrame frame = new JFrame("Tabela do Empreendimento");
        
        JTable table = new JTable(Data.getData().dadosModel);
        JScrollPane scrollPane = new JScrollPane(table);
        scrollPane.add(table.getTableHeader());
        table.setFillsViewportHeight(false);
 
        Data.getData().dadosModel.addTableModelListener(
        new TableModelListener() 
        {
            public void tableChanged(TableModelEvent evt) 
            {
                Data.getData().dadosModel.atualizarVariaveis();
            }
        });
        
        JLabel lblHeading = new JLabel("Empreendimento");
        lblHeading.setFont(new Font("Arial",Font.TRUETYPE_FONT,24));
        JButton calcular = new JButton("Calcular");
        calcular.addMouseListener(new MouseListener() {

            @Override
            public void mouseClicked(MouseEvent e) {
                if(table.getCellEditor()!=null)
                table.getCellEditor().stopCellEditing();
                Data.getData().dadosModel.atualizarVariaveis();
                JFrame fAdvanced = new JFrame();
                TaxaSelic cfp = new TaxaSelic(fAdvanced);
                fAdvanced.setSize(cfp.getPreferredSize());
                fAdvanced.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                fAdvanced.add(cfp);
                fAdvanced.setLocationRelativeTo(pt);
                fAdvanced.setVisible(true);
            }

            @Override
            public void mousePressed(MouseEvent e) {
                
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                
            }

            @Override
            public void mouseExited(MouseEvent e) {
                
            }
        });
        this.setLayout(new BorderLayout());
 
        this.add(lblHeading,BorderLayout.NORTH);
        this.add(calcular,BorderLayout.SOUTH);
        this.add(scrollPane,BorderLayout.CENTER);
 
        
        this.setSize(550, 200);
        this.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1304, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
